spring:
  profiles: mobile-carriers

simple-messaging-service:
  carriers:
    verizon:
      id: verizon
      name: Verizon Wireless
      smsDomain: vtext.com
      mmsDomain: vzwpix.com
    att:
      id: att
      name: AT&T
      smsDomain: txt.att.net
      mmsDomain: mmsDomain.att.net
    sprint:
      id: sprint
      name: Sprint
      smsDomain: messaging.sprintpcs.com
      mmsDomain: pm.sprint.com
    tmobile:
      id: tmobile
      name: T-Mobile
      smsDomain: tmomail.net
      mmsDomain: tmomail.net
    virgin:
      id: virgin
      name: Virgin Wireless
      smsDomain: vmobl.com
      mmsDomain: vmpix.com
    xfinity:  
      id: xfinity
      name: X-Finity
      smsDomain: vtext.com
      mmsDomain: mypixmessages.com   
    tracfone: 
      id: tracfone 
      name: Tracfone
      smsDomain: NOT_SETUP
      mmsDomain: mmsDomaint5.tracfone.com
    metropcs:
      id: metropcs 
      name: Metro PCS
      smsDomain: mymetropcs.com
      mmsDomain: mymetropcs.com
    boostmobile:
      id: boostmobile 
      name: Boost Mobile
      smsDomain: smsDomain.myboostmobile.com
      mmsDomain: myboostmobile.com
    cricket:
      id: cricket
      name: Cricket Wireless
      smsDomain: smsDomain.cricketwireless.net
      mmsDomain: mmsDomain.cricketwireless.net
    republic:
      id: republic
      name: Republic Wireless 
      smsDomain: text.republicwireless.com
      mmsDomain: NOT_SETUP
    googlefi:
      id: googlefi 
      name: Google Project FI
      smsDomain: msg.fi.google.com
      mmsDomain: msg.fi.google.com
    uscellular:
      id: uscellular 
      name: U.S. Cellular
      smsDomain: email.uscc.net
      mmsDomain: mmsDomain.uscc.net 
    ting:
      id: ting
      name: Ting 
      smsDomain: message.ting.com
      mmsDomain: NOT_SETUP
    consumer:
      id: consumer
      name: Consumer Cellular 
      smsDomain: mailmymobile.net
      mmsDomain: NOT_SETUP
    cspire:
      id: cspire 
      smsDomain: cspire1.com
      mmsDomain: NOT_SETUP
    pageplus:
      id: pageplus 
      name: Page Plus
      smsDomain: vtext.com
      mmsDomain: NOT_SETUP    
    alltel:
      id: alltel
      name: Alltel
      smsDomain: message.alltel.com
      mmsDomain: mmsDomain.alltelwireless.com
    straighttalk:
      id: straighttalk
      name: Straight Talk
      smsDomain: vtext.com
      mmsDomain: mypixmessages.com
  
#::END::