spring:
  profiles: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(+NrGOr6Xv53rPwlMoqGpCynBhlfDOYXQhssEqPKZcOk=)
    password: ENC(ii/qJSCGxX++HEfHzXS0+w7Rb0e0RyvyED8PiWxqsP0=)
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false
        
# Spring Boot actuator         
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - shutdown

# Spring Boot Embedded Tomcat Server
server:
    address: 0.0.0.0
    port: 1080

# Simple Messaging Service 
simple-messaging-service:
  smtpServer:
    softwareName: Simple SMTP Server
    port: 1025
    timeout: 120
  
      
#::END::
      
      